<a href="https://colab.research.google.com/github/bacdam91/mxnet-tutorial/blob/master/Manipulate_data_with_ndarray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install mxnet

     |████████████████████████████████| 25.4MB 1.4MB/s 
  Found existing installation: graphviz 0.10.1
    Uninstalling graphviz-0.10.1:
      Successfully uninstalled graphviz-0.10.1


### About NDArray

```NDArray``` is MXNet's primary tool for storing and transforming data. By design ```NDArray``` is similar to ```NumPy```'s multi-dimensional array.

### Importing ```NDArray``` from ```MXNet```

In order to use ```NDArray```, we will have to import it from ```mxnet``` package.

In [0]:
from mxnet import nd

### Creating arrays/matrices from arrays and tuples
An array can be created from tuples/arrays of tuples or arrays or combination of both. 

The elements can be of ```int``` or ```float``` type, or is parse-able into those two types, i.e., ```'1'``` but not ```'a'```.

In [0]:
# Tuple of tuples
m = ((1, 2, 3), (4, 5, 6))
M = nd.array(m)
display(M)

# Array of arrays
n = [[1.2, 2.3], [3.4, 4.5]]
N = nd.array(n)
display(N)

# Array of tuple and array
o = [('1', '2.7'), [3, 4]]
O = nd.array(o)
display(O)


[[1. 2. 3.]
 [4. 5. 6.]]
<NDArray 2x3 @cpu(0)>


[[1.2 2.3]
 [3.4 4.5]]
<NDArray 2x2 @cpu(0)>


[[1.  2.7]
 [3.  4. ]]
<NDArray 2x2 @cpu(0)>

### Creating arrays/matrices filled with one specific value

```NDArray``` provides us with convenient methods to generate a matrix of certain ```shape``` and fill it with 0s, 1s or any value.

The ```x_shape``` can be either a tuple or an array with length of 2, i.e., [rows, cols].

In [0]:
shape = [3, 5]

X0 = nd.zeros(shape)
X1 = nd.ones(shape)
Xn = nd.full(shape, 3.141)

display(X0)
display(X1)
display(Xn)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
<NDArray 3x5 @cpu(0)>


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
<NDArray 3x5 @cpu(0)>


[[3.141 3.141 3.141 3.141 3.141]
 [3.141 3.141 3.141 3.141 3.141]
 [3.141 3.141 3.141 3.141 3.141]]
<NDArray 3x5 @cpu(0)>

### Creating arrays/matrices with random values over a range

```NDArray``` also provides us with a convenient way to generate an array/matrix of any shape filled uniformly with values between a specified range.

The example below shows the generation of a matrix with 4 rows and 2 columns and with random values between -2 and 2.

In [0]:
shape = (4, 2)
lower_bound = -2
upper_bound = 2

Y = nd.random.uniform(lower_bound, upper_bound, shape)
display(Y)


[[0.19525409 0.37137842]
 [0.86075735 1.377063  ]
 [0.41105342 1.4317825 ]
 [0.17953277 1.3890069 ]]
<NDArray 4x2 @cpu(0)>

### The ```.argmax()``` method

When we do classification problems with neural networks, the network does not actually tell us if something is of a certain type but instead the probability the the subject is of a certain type, i.e., what is the chance that the image is an image of a dog?. 

Using an example of a classifier of images for dogs or cats, if the probability of the image being that of a dog is 0.9 then the probability of the image being that of a cat is 0.1. The neural network returns this probability as an array of probability, e.g. 

```classes = ["dog", "cat"]```

```prediction = [0.9, 0.1]```

The index of the probability correspond to its class defined in the ```classes``` array. 

Instead of using a complex for loop to find the index of the highest value, we can use the ```.argmax()``` method.

In [23]:
classes = ["dog", "cat"]

prediction = nd.array([[0.9, 0.1]])

idx = prediction.argmax(axis=1)

classes[int(idx.asscalar())]

'dog'

When we call ```.argmax()``` on an array of multiple arrays, i.e., multiple predictions, we get back an array of same length but with the highest value of each row. 

In [25]:
array_a = nd.array([[0.1, 0.9], [0.2, 0.8], [0.6, 0.4]])
idx = array_a.argmax(axis=1)
idx


[1. 1. 0.]
<NDArray 3 @cpu(0)>

### Comparing arrays

```NDArray``` allows us to perform elementwise comparison of two arrays. This means we can take two arrays of same length and compare an element in one ```NDArray``` to another element in another ```NDArray``` which has the same index. The output is an array of 0s and 1s, where 0 represents ```False``` and 1 represents ``` True```.

In [37]:
labels = nd.array([1, 1, 1])
score = (labels == idx)
print(score)


[1. 1. 0.]
<NDArray 3 @cpu(0)>


### Operations on ```NDArray```

We can also perform mathematical and statistical operations on an ```NDArray``` such as ```.mean()```, ```.sum()```, ```reciprocal()``` and ```.abs()```.

In [43]:
an_array = nd.array([1, 2, -4, -1, 5])

print("Mean: ", an_array.mean())
print("Sum: ", an_array.sum())
print("Reciprocal: ", an_array.reciprocal())
print("Aboslute: ", an_array.abs())

Mean:  
[0.6]
<NDArray 1 @cpu(0)>
Sum:  
[3.]
<NDArray 1 @cpu(0)>
Reciprocal:  
[ 1.    0.5  -0.25 -1.    0.2 ]
<NDArray 5 @cpu(0)>
Aboslute:  
[1. 2. 4. 1. 5.]
<NDArray 5 @cpu(0)>


### Inspecting arrays/matrices

```NDArray``` arrays/matrices have aattributes that can help us to inspect them. These include:

1. ```.shape``` tells us the number of rows and columns.
2. ```.size``` tells us the number of 'cells', i.e., the product of rows and columns.
3. ```.dtype``` tells us the data type of the values stored

In [0]:
print(f"Shape of y (rows, cols): {Y.shape}")
print(f"Size of y (rows x cols): {Y.size}")
print(f"Data type of y's elements: {Y.dtype}")

Shape of y (rows, cols): (4, 2)
Size of y (rows x cols): 8
Data type of y's elements: <class 'numpy.float32'>


### Matrix Operations

```NDArray``` supports many standard mathematical operations, such as:

#### Element-wise multiplication

Also known as Hadamard product, Schur product and entrywise product.

In [0]:
X = nd.full([3, 4], 2)
Y = nd.full([3, 4], 1.5)
Z = X * Y
display(Z)


[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]
<NDArray 3x4 @cpu(0)>

#### Exponentiation

Each element within is used as the power to $e$.

For example, consider matrix $A$ which has 2 rows and 2 columns. The first row has the values 1 and 2, and the second row has the values 3 and 4. 

When we use the method ```.exp()```, ```NDArray``` takes each element as the power of $e$.

1. $e^{1} = 2.718$
2. $e^{2} = 7.389$
3. $e^{3} = 20.08$
4. $e^{4} = 54.59$

In [0]:
A = nd.array([[1, 2], [3, 4]])
A.exp()


[[ 2.7182817  7.389056 ]
 [20.085537  54.59815  ]]
<NDArray 2x2 @cpu(0)>

#### Cross product

Despite the naming of the function, ```nd.dot()``` , this function calculates the cross product of two matrices.

As such the number of columns of the first matrix must equals the number of rows of the second matrix, otherwise an error will be thrown.

In [0]:
X = nd.array([[1, 2, 3], [1, 2, 3]])
Y = nd.array([[3, 5], [4, 4], [5, 3]])
nd.dot(X, Y)


[[26. 22.]
 [26. 22.]]
<NDArray 2x2 @cpu(0)>

### Matrix's transpose

We can also use the matrix's transpose to compute the cross product.

The example below is very similar to the one above, except that the ```Y``` matrix has 2 rows and 3 columns, instead of 3 rows and 2 columns as above.

If we just compute the cross product of ```X``` and ```Y``` we would not be able to, as per explanation above. As such we need to get the transpose of ```Y``` with ```Y.T``` so that we get a matrix of 3 rows and 2 columns.

In [0]:
X = nd.array([[1, 2, 3], [1, 2, 3]])
Y = nd.array([[3, 4, 5], [5, 4, 3]])

display(Y)
display(Y.T)

nd.dot(X, Y.T)


[[3. 4. 5.]
 [5. 4. 3.]]
<NDArray 2x3 @cpu(0)>


[[3. 5.]
 [4. 4.]
 [5. 3.]]
<NDArray 3x2 @cpu(0)>


[[26. 22.]
 [26. 22.]]
<NDArray 2x2 @cpu(0)>

### Indexing

```NDArray``` provides a lot of flexibility when it come to accessing our data. The sliced portion is returned as an array, even if it's just a single value we are after.

Below we are trying to get the element in the 2nd row and 3rd column.

In [0]:
Y = nd.array([[1, 2, 3], [4, 5, 6]])
display(Y)

# Get the value in 2nd row and 3rd column (remember Python's index starts with 0)
Y[1,2]


[[1. 2. 3.]
 [4. 5. 6.]]
<NDArray 2x3 @cpu(0)>


[6.]
<NDArray 1 @cpu(0)>

Example below shows we can read all rows from the 2nd column to and including the 3rd column.

In [0]:
display(Y)
Y[:,1:3]


[[1. 2. 3.]
 [4. 5. 6.]]
<NDArray 2x3 @cpu(0)>


[[2. 3.]
 [5. 6.]]
<NDArray 2x2 @cpu(0)>

We can write to the selected region with ease.

The example below shows the same region will now have the value 3.141.

In [0]:
display(Y)
Y[:,1:3] = 3.141
display(Y)


[[1. 2. 3.]
 [4. 5. 6.]]
<NDArray 2x3 @cpu(0)>


[[1.    3.141 3.141]
 [4.    3.141 3.141]]
<NDArray 2x3 @cpu(0)>

We can even slice and write multi-dimensionally.

The example below shows the elements in the 2nd row and 1st and 2nd column are overriden with a new value.

In [0]:
display(Y)
Y[1:2,0:2] = 1.618
display(Y)


[[1.    3.141 3.141]
 [1.618 1.618 3.141]]
<NDArray 2x3 @cpu(0)>


[[1.    3.141 3.141]
 [1.618 1.618 3.141]]
<NDArray 2x3 @cpu(0)>

### Converting between ```MXNet NDArray``` and ```NumPy```

Converting between ```MXNet NDArray``` and ```NumPy``` arrays is a breeze. The converted arrays do not share memory.

In [0]:
X = nd.array([[9, 8, 7], [6, 5, 4]])
A = X.asnumpy()

(type(A), A)

(numpy.ndarray, array([[9., 8., 7.],
        [6., 5., 4.]], dtype=float32))

In [0]:
nd.array(A)


[[9. 8. 7.]
 [6. 5. 4.]]
<NDArray 2x3 @cpu(0)>